project:
  type: website

website:
  title: "Wimbledon 2023 Prediction"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - page1.qmd
      - page2.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



